JewelOfIndiaBuilder/Controllers/VisualAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JewelOfIndiaBuilder.Models;

namespace JewelOfIndiaBuilder.Controllers
{
    public class VisualAdminController : Controller
    {
        private JewelOfIndiaEntities db = new JewelOfIndiaEntities();

        // GET: /VisualAdmin/
        public ActionResult Index(string Type, string Id)
        {
            ViewData.Add("Type", Type);
            ViewData.Add("Id", Id);
            Int32 TypeId = Convert.ToInt32(Id);

            if (Type == "Property")
            {
                return View(db.Visuals.Where(v => v.Type.Equals("P") && v.TypeId.Equals(TypeId)).ToList());
            }
            if (Type == "Tower")
            {
                return View(db.Visuals.Where(v => v.Type.Equals("T") && v.TypeId.Equals(TypeId)).ToList());
            }
            if (Type == "Apartment")
            {
                return View(db.Visuals.Where(v => v.Type.Equals("A") && v.TypeId.Equals(TypeId)).ToList());
            }
            return View(db.Visuals.ToList());
        }

        // GET: /VisualAdmin/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visual visual = db.Visuals.Find(id);
            if (visual == null)
            {
                return HttpNotFound();
            }
            return View(visual);
        }

        // GET: /VisualAdmin/Create
        public ActionResult Create(string Type, string Id)
        {
            ViewData.Add("Type", Type);
            ViewData.Add("Id", Id);
            return View();
        }

        // POST: /VisualAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IEnumerable<HttpPostedFileBase> files)
        {
            string type = "";
            string id = "";
            string typevalue = "";
            type = Request.Form["Type"];
            id = Request.Form["Id"];
            if (type == "Property")
            {
                typevalue = "P";
            }
            if (type == "Tower")
            {
                typevalue = "T";
            }
            if (type == "Apartment")
            {
                typevalue = "A";
            }
            if (ModelState.IsValid)
            {
                for(int i=0;i<Request.Files.Count;i++)
                {
                    string path = @"..\..\Images\";

                    HttpPostedFileBase photo = Request.Files[i];

                    if (photo != null && photo.ContentLength != 0)
                    {
                        var file = Guid.NewGuid() + photo.FileName.Substring(photo.FileName.IndexOf('.'), 4);
                        var fileName = Path.Combine(Server.MapPath(path),file); 
                        photo.SaveAs(fileName);
                        var v = new Visual
                        {
                            DisplayName = photo.FileName,
                            Name = fileName,
                            Type = typevalue,
                            TypeId = Convert.ToInt64(id)
                        };
                        db.Visuals.Add(v);
                        try
                        {
                            db.SaveChanges();
                        }
                        catch (DbEntityValidationException e)
                        {
                            foreach (var eve in e.EntityValidationErrors)
                            {
                                Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                                    eve.Entry.Entity.GetType().Name, eve.Entry.State);
                                foreach (var ve in eve.ValidationErrors)
                                {
                                    Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                        ve.PropertyName, ve.ErrorMessage);
                                }
                            }
                            throw;
                        }
                       
                    }


                }
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: /VisualAdmin/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visual visual = db.Visuals.Find(id);
            if (visual == null)
            {
                return HttpNotFound();
            }
            return View(visual);
        }

        // POST: /VisualAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ImageName")] Visual visual)
        {
            if (ModelState.IsValid)
            {
                db.Entry(visual).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(visual);
        }

        // GET: /VisualAdmin/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visual visual = db.Visuals.Find(id);
            if (visual == null)
            {
                return HttpNotFound();
            }
            return View(visual);
        }

        // POST: /VisualAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Visual visual = db.Visuals.Find(id);
            db.Visuals.Remove(visual);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            if (filterContext != null && filterContext.Exception != null)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(filterContext.Exception);
                filterContext.ExceptionHandled = true;
                this.View("Error").ViewData["Exception"] = filterContext.Exception.Message;
                this.View("Error").ExecuteResult(this.ControllerContext);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JewelOfIndiaBuilder/Views/VisualAdmin/Create.cshtml
@model JewelOfIndiaBuilder.Models.Visual

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "VisualAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <label class="control-label col-md-2" for="label">Add Image for : </label><input type="text" readonly = "true" name ="Type" id="Type" value ="@ViewBag.Type" /><br />
    <label class="control-label col-md-2" for="label">@ViewBag.Type : Id</label><input type="text" readonly = "true" name ="Id" id="Id" value ="@ViewBag.Id" /><br />
    <label class="control-label col-md-2" for="file">Upload Image 1:</label> <input type="file" name="[0].files" id="files_0" style="width: 50%;" /><br />
    <label class="control-label col-md-2" for="file">Upload Image 2:</label> <input type="file" name="[1].files" id="files_1" style="width: 100%;" /><br />
    <label class="control-label col-md-2" for="file">Upload Image 3:</label> <input type="file" name="[2].files" id="files_2" style="width: 100%;" /><br />
    <label class="control-label col-md-2" for="file">Upload Image 4:</label> <input type="file" name="[3].files" id="files_3" style="width: 100%;" /><br />
    <label class="control-label col-md-2" for="file">Upload Image 5:</label> <input type="file" name="[4].files" id="files_4" style="width: 100%;" /><br />
    <label class="control-label col-md-2" for="file">Upload Image 6:</label> <input type="file" name="[5].files" id="files_5" style="width: 100%;" /><br />
    <label class="control-label col-md-2" for="file">Upload Image 7:</label> <input type="file" name="[6].files" id="files_6" style="width: 100%;" /><br />
    <label class="control-label col-md-2" for="file">Upload Image 8:</label> <input type="file" name="[7].files" id="files_7" style="width: 100%;" /><br />
    <label class="control-label col-md-2" for="file">Upload Image 9:</label> <input type="file" name="[8].files" id="files_8" style="width: 100%;" /><br />
    <label class="control-label col-md-2" for="file">Upload Image 10:</label> <input type="file" name="[9].files" id="files_9" style="width: 100%;" /><br />
    <input class="btn btn-default" type="submit" value="Upload" class="submit" />

    
        @Html.ValidationSummary(true)

        @*<div class="form-group">
            @Html.LabelFor(model => model.Id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id)
                @Html.ValidationMessageFor(model => model.Id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageName)
                @Html.ValidationMessageFor(model => model.ImageName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>*@
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JewelOfIndiaBuilder/Views/VisualAdmin/Delete.cshtml
@model JewelOfIndiaBuilder.Models.Visual

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Visual</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DisplayName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisplayName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JewelOfIndiaBuilder/Views/VisualAdmin/Details.cshtml
@model JewelOfIndiaBuilder.Models.Visual

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Visual</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DisplayName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisplayName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JewelOfIndiaBuilder/Views/VisualAdmin/Edit.cshtml
@model JewelOfIndiaBuilder.Models.Visual

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Visual</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.DisplayName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DisplayName)
                @Html.ValidationMessageFor(model => model.DisplayName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JewelOfIndiaBuilder/Views/VisualAdmin/Index.cshtml
@model IEnumerable<JewelOfIndiaBuilder.Models.Visual>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink(
    linkText: "Create New",
    actionName: "Create",
    controllerName: "VisualAdmin",
    routeValues: new {
        Type = ViewBag.Type, 
        Id = ViewBag.Id
    },
    htmlAttributes: null
)
    
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DisplayName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img width="100px" height="100px" src  ="..\..\images\@Html.DisplayFor(modelItem => item.DisplayName)"/>
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>